// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iriotlxdjtavqsdqdbfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyaW90bHhkanRhdnFzZHFkYmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mjc2NDgsImV4cCI6MjA2NDIwMzY0OH0.YhjcS53QNJQG3il8vteBeEXEZfo8YR5ItkXi8eDNl7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);